name: FlyPlugin
version: 1.0
main: me.argonyte.flyplugin.FlyPlugin
api-version: 1.13
authors: [Argonyte]
description: Simple Fly Plugin
commands:
  fly:
    description: Fly command gives access to fly to the player.
    usage: /<command>
